version: '3.8'

name: ollivanders-database

services:
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql-server
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword123!
      - MSSQL_PID=Developer
      - MSSQL_USER=SA